baseURL = "https://coders.school/hugo"
# website language
languageCode = "pl"
# [en, zh, ...] determines which i18n file to use
defaultContentLanguage = "pl"
# website title
title = "Coders School - Szkoła prawdziwego C++"
# theme
theme = "LoveIt"
# whether to use git commit log to generate lastmod record
enableGitInfo = true
# whether to include chinese/japanese/korean
hasCJKLanguage = false
# default amount of posts in each pages
paginate = 12
# whether to use emoji code
enableEmoji = true
# whether to use robots.txt
enableRobotsTXT = true
# [UA-XXXXXXXX-X] google analytics code
googleAnalytics = "UA-9751224-5"
# copyright description used only for seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
# date format
dateFormatToUse = "2006-01-02"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "github"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
[author]                                              #### Author Info
  name = "Łukasz Ziobroń"
  link = "https://coders.school/o-nas/#trenerzy"

# Sitemap Info
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  posts = ":filename"

# Menu Info
[menu]                                                #### Menu Info
  [[menu.main]]
    identifier = "kurs-cpp"
    name = "Kurs C++ stacjonarny"
    url = "https://coders.school/kursy/"
    weight = 1

  [[menu.main]]
    identifier = "kurs-online"
    name = "Kurs C++ online"
    url = "https://coders.school/kurs-online/"
    weight = 2

  [[menu.main]]
    identifier = "sprawdz-sie"
    name = "Test C++"
    url = "https://coders.school/sprawdz-sie/"
    weight = 3

  [[menu.main]]
    identifier = "materialy"
    name = "Książki"
    url = "resources"
    weight = 4

  [[menu.main]]
    identifier = "poradnik"
    name = "Poradnik"
    url = "https://coders.school/poradnik/"
    weight = 5

  [[menu.main]]
    identifier = "o-nas"
    name = "O nas"
    url = "https://coders.school/o-nas/"
    weight = 6

  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "https://coders.school/faq/"
    weight = 7

  [[menu.main]]
    identifier = "kontakt"
    name = "Kontakt"
    url = "https://coders.school/o-nas#kontakt/"
    weight = 8


[params]
  # LoveIt theme version
  version = "0.1.X"
  # site description
  description = "Uczymy prawdziwego i nowoczesnego C++"
  # site keywords
  keywords = ["C++", "kurs C++", "szkoła C++", "nauka C++", "C++ dla początkujących", "C++ dla zaawansowanych", "C++ dla ekspertów"]

  # Home Page Info
  ## [post, other] home mode
  home_mode = "post"
  ## special amount of posts in each home post page
  home_paginate = 6
  ## URL of avatar shown in home page
  avatar = "images/avatar.png"
  ## subtitle shown in home page
  subtitle = "Uczymy prawdziwego i nowoczesnego C++"

  # whether to show social share links in post page
  socialShare = true

  # Footer CopyRight Info
  ## Site creation time
  since = 2017
  ## ICP info only in China (HTML format is allowed)
  icp = ""
  ## license info (HTML format is allowed)
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # public git repo url to link lastmod git commit only then enableGitInfo is true
  gitRepo = "https://github.com/coders-school/site.git"

  # mathematical formulas (KaTeX)
  [params.math]
    enable = true
    block_left_delimiter = ""
    block_right_delimiter = ""
    inline_left_delimiter = "$"
    inline_right_delimiter = "$"
    # KaTeX extension copy_tex
    copy_tex = true
    # KaTeX extension mhchem
    mhchem = true

  # whether to show link to Raw Markdown content of the post
  linkToMarkdown = true

  # site verification code for Google/Bing/Yandex/Pinterest/Baidu
  google_verification = "7awM6eOkKNNpFMKM4jPdfyNxJkjPNYgm3IqR_ML8loY"
  bing_verification = ""
  yandex_verification = ""
  pinterest_verification = ""
  baidu_verification = ""

  # CSS and JS Files CDN
  [params.cdn]
    ## for example '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">'
    fontawesome_free_css = ''
    animate_css = ''
    gitalk_css = ''
    gitalk_js = ''
    valine_js = ''
    jquery_js = ''
    lazysizes_js = ''
    smooth_scroll_js = ''
    katex_css = ''
    katex_js = ''
    katex_auto_render_js = ''
    katex_copy_tex_css = ''
    katex_copy_tex_js = ''
    katex_mhchem_js = ''
    mermaid_js = ''
    echarts_js = ''
    echarts_macarons_js = ''
    typeit_js = ''
    jquery_countdown_js = ''
    aplayer_css = ''
    aplayer_js = ''
    meting_js = ''

  # Gravatar Info for preferred avatar in home page
  [params.gravatar]
    email = ""

  # Social Info in home page
  [params.social]
    GitHub = "coders-school"
    Linkedin = "lukaszziobron"
    #Twitter = "xxxx"
    #Instagram = "xxxx"
    Email = "lukasz@coders.school"
    Facebook = "szkola.coders.school"
    #Telegram = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    Youtubechannel = "UCVazq4NfH8l4BW_qLEoJy-A"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "xxxx"
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #FreeCodeCamp = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    #Mastodon = "xxxx"
    #Thingiverse = "xxxx"
    #Devto = "xxxx"
    #Gitea = "xxxx"
    #XMPP = "xxxx"
    #Matrix ="xxxx"

  # Social Share Links in post page
  [params.share]
    enable = true
    Twitter = true
    Facebook = true
    Reddit = true
    #Linkedin = true
    #Pinterest = true
    #HackerNews = true
    #Mix = true
    #Tumblr = true
    #VKontakte = true
    #Weibo = true

  # Publisher Info just for SEO
  [params.publisher]
    name = "Łukasz Ziobroń"
    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  # Website Log Info just for SEO
  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  # Website Image Info just for SEO
  [params.image]
    url = "cover.png"
    width = 800
    height = 600

  # Disqus Comment Config (https://disqus.com/)
  [params.disqus]
    # Disqus shortname to use Disqus in posts
    shortname = "ukasz_z"

  # Gittalk Comment Config (https://github.com/gitalk/gitalk)
  [params.gitalk]
    owner = ""
    repo = ""
    clientId = ""
    clientSecret = ""

  # Valine Comment Config (https://github.com/xCss/Valine)
  [params.valine]
    enable = false
    appId = ""
    appKey = ""
    notify = false
    verify = true
    avatar = "mp"
    placeholder = "Your comment ..."
    visitor = true
    recordIP = true

  # Facebook Comment Config (https://developers.facebook.com/docs/plugins/comments)
  [params.facebook]
    enable = false
    width = "100%"
    numPosts = 10
    appId = ""
    languageCode = "en_US"

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
